### PR TITLE
Register team knock-knock

### PR DESCRIPTION
**Pull request by dr3dd589**

### CODE REVIEW

**Comment by eltci** [comment]
Sorry. A failure has occurred when processing your proposal. Please contact support and present the following info:

**Stream name**: 2018/11/29/[$LATEST]ab0bbdb9faab4069b9d78cdf7b0ff462
**Request ID**: 465a0f0b-f3b4-11e8-a587-83fa04fc9b2c

**Comment by thotypous** [comment]
@drd3dd589 Sorry, we only allow a single team to be registered per GitHub user. If you prefer to rename your team, or if you lost credentials for your previous registration (#10) please tell us so that we can remove it.

**Comment by dr3dd589** [comment]
Yes please, remove previous team i lost it credentials..!!

**Comment by thotypous** [comment]
@dr3dd589 Done! please register again

**Pull request closed without merging**
