### PR TITLE
Register team SiBears

### PR DESCRIPTION
**Pull request by v-lebedev**

### CODE REVIEW

**Comment by Stanleystarsly** [comment]
@hacker-volodya 
@eltci @gmunkhbaatarmn @eltci @afonso @dudis @hacker-volodya 
@eltci [](url)

**Comment by Stanleystarsly** [comment]
👋 Hi, I’m @Stanleystarsly
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...


-# 👋 Hi, I’
- 👀 I’m interested in ...coding
- ##🌱 I’m currently learning ...coding
- 💞️ I’m looking to collaborate on ...coding
- 📫 How to reach me ... stanleystarsly8@gmail.com 2347043744412

**Comment by Stanleystarsly** [comment]
> @hacker-volodya @eltci @gmunkhbaatarmn @eltci @afonso @dudis @hacker-volodya @eltci

👋 Hi, I’m @Stanleystarsly
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...


- 👋 Hi, I’m @Stanleystarsly
- 👀 I’m interested in ...coding
- 🌱 I’m currently learning ...coding
- 💞️ I’m looking to collaborate on ...coding
- 📫 How to reach me ... stanleystarsly8@gmail.com 2347043744412

**Comment by dbnayem** [comment]
0x4b7a1e22d2e1f3158dee9e0435302d4981cb7270

**Comment by dbnayem** [comment]
0x4b7a1e22d2e1f3158dee9e0435302d4981cb7270

**Comment by dbnayem** [comment]
UQB7sIqcyU3oX_1FWs6p_YLzJVfD34BkslXCsT5AEH_-cB8P

**Comment by dbnayem** [comment]
UQAAJlaAvu5I8BJgThs4RwlbOPRiDa_f3_ZRDaTyD_O9GdQY

**Comment by Edgar71769** [comment]
7

**Pull request merged**
