### PR TITLE
Proof: found flag for g00d_b0y

### PR DESCRIPTION
**Pull request by bleleet**

### CODE REVIEW

**Comment by eltci** [comment]
Sorry. A failure has occurred when processing your proposal. Please contact support and present the following info:

**Stream name**: 2018/12/01/[$LATEST]f0a5356a4f97415589ee426f0a6cf024
**Request ID**: 6ed9a2bd-f552-11e8-a91c-53af202f4cea

**Comment by eltci** [comment]
Sorry. A failure has occurred when processing your proposal. Please contact support and present the following info:

**Stream name**: 2018/12/01/[$LATEST]f0a5356a4f97415589ee426f0a6cf024
**Request ID**: a1530da6-f555-11e8-9a99-b965a9863ba2

**Comment by thotypous** [comment]
I don't know if this was intentional (were you trying to test the security of the game platform?) but the https://github.com/bleleet/2018submissions/raw/cf44597fab12c56a066f71ce75543ed3ef50b031/e/1b6/724ca4994b37e525c172f2ed147bb01202942ac68f424ec9180f999590ef/submissions.csv file contains lot of "\x00" chars. This is the reason it was rejected.

**Comment by bleleet** [comment]
I do not know why.
How to fix it ..

**Pull request closed without merging**
